name: Fetch Contributors

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  fetch-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Run Fetch Contributors Script
        run: node scripts/fetchContributors.js
        env:
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
